spring:
  application:
    name: user-center

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thr
    username: root
    password: xxx

server:
  port: 8080


